name: release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 14
        java-package: jre

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./mill common.publishArtifactory --credentials lavrov:${{ secrets.GITHUB_TOKEN }}
        ./mill common.js.publishArtifactory --credentials lavrov:${{ secrets.GITHUB_TOKEN }}
        ./mill dht.publishArtifactory --credentials lavrov:${{ secrets.GITHUB_TOKEN }}
        ./mill bittorrent.publishArtifactory --credentials lavrov:${{ secrets.GITHUB_TOKEN }}
