name: release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        distribution: 'adopt'
        java-version: graalvm-ce-java11@20.1.0

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sbt commonJVM/publish
        sbt commonJS/publish
        sbt bittorrent/publish
        sbt dht/publish
        sbt tracker/publish
